stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - echo "Execute this command before any 'script:' commands."
    - apt-get update
    - apt-get install  --yes xutils-dev gcc make flex bison graphviz
  script:
    - echo "Compiling the code..."
    - make 
    - echo "Compile complete."
  only:
    - merge_requests
  

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - apt-get update
    - apt-get install  --yes xutils-dev gcc make flex bison graphviz  
  script:
    - make # peut-être inutile
    - echo "Running unit tests... This will take about 60 seconds."
    - make test ARGS=1
    - make test ARGS=2
    - make test ARGS=3
    - echo "Tests are passed"
  only:
    - merge_requests

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  only:
    - merge_requests