stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - echo "Installation des paquets"
    - apt-get update
    - apt-get install  --yes xutils-dev gcc make flex bison graphviz
  script:
    - echo "Compilation .. "
    - make 
    - echo "Compilation OK "
  only:
    - merge_requests
  

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  before_script:
    - apt-get update
    - apt-get install  --yes xutils-dev gcc make flex bison graphviz  
  script:
    - make # peut-être inutile
    - echo "Tests lex .. "
    - make test_lex ARGS=1
    - make test_lex ARGS=2
    - make test_lex ARGS=3
    - echo "Tests lex OK "
    - echo "Tests yacc .. "
    - make test_yacc ARGS=1
    - make test_yacc ARGS=2
    - make test_yacc ARGS=3
    - echo "Tests yacc OK "
  only:
    - merge_requests

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploiement "
    - echo "Deploiement OK "
  only:
    - merge_requests