default:
	image: ubuntu:20.04

stages:
	- build
	- tests
	- validate_tasks

build_code:
	stage: build
	before-script : 
		- apt-get update
		- apt-get install --yes xutils-dev gcc make flex bison graphviz
	script:
		- make

build_doc: # juste pour notifier l'installation de graphviz pour le moment inclut
	stage: build	# dans le all du make
	before-script :
		- apt-get update
		- sudo apt-get install --yes xutils-dev gcc make flex bison  graphviz
	script:
		- make doc_m

verif_style:
	stage: build
	before_script:
		- apt-get update
		- apt-get install --yes --force-yes xutils-dev gcc make
	script:
		- make #puis ajout d'un script qui detecte les tabulations 

	only:
		- merge_requests
		
				
test_a: 
	stage: tests
	needs: [build_code]
	script:
		- echo "Lancement du test de niveau 1 "

test_b:
	stage: tests
	needs: [build_code]	
	script:
		- echo "Lancement du test de niveau 2 "
	

test_c:
	stage: tests
	needs: [build_code]
	script:
		- echo "Lancement du test de niveau 3"
		
tests:
	stage: tests
	needs:
		- test_a
		- test_b
		- test_c
		

validation:
	stage: validate_tasks
	needs: 
		- tests
		- verif_style 
	script:
		- echo "Tâche valide"

	only: 
		refs:
			- merge_requests
		changes:
			- code/*


